name: esp32 port

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_idf44:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Clone lv_micropython repository
      run: git clone https://github.com/lvgl/lv_micropython.git
    - name: Initialize lv_bindings submodule
      run: cd lv_micropython && git submodule update --init --recursive lib/lv_bindings
    - name: Install packages
      run: cd lv_micropython && source tools/ci.sh && ci_esp32_idf44_setup
    - name: Build
      run: cd lv_micropython && source tools/ci.sh && ci_esp32_build
