name: lala

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_idf44:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone lv_micropython repository
      run: git clone https://github.com/lvgl/lv_micropython.git
    
    - name: Initialize lv_bindings submodule
      run: |
        cd lv_micropython 
        git submodule update --init --recursive lib/lv_bindings
    
    - name: Install packages
      run: |
        cd lv_micropython 
        source tools/ci.sh 
        ci_esp32_idf44_setup
    
    - name: Add custom board configuration (ESP32_GENERIC_S3_N16R8)
      run: |
        cp -r ESP32_GENERIC_S3_N16R8 lv_micropython/ports/esp32/boards/
        ls lv_micropython/ports/esp32/boards/
        echo $GITHUB_WORKSPACE
    
    - name: Build for ESP32_GENERIC_S3_N16R8
      run: |
        source esp/esp-idf/export.sh
        cd lv_micropython/
        make -C mpy-cross
        export IDF_TARGET=esp32s3
        cd ports/esp32/
        idf.py -D LV_CFLAGS="-DLV_COLOR_DEPTH=16" \
               -D MICROPY_BOARD=ESP32_GENERIC_S3_N16R8 \
               -D MICROPY_BOARD_DIR="boards/ESP32_GENERIC_S3_N16R8" \
               build

    - name: Move binaries
      run: |
        mkdir -p ./artifacts
        cp lv_micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8/micropython.bin ./artifacts/
        cp lv_micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8/bootloader/bootloader.bin ./artifacts/
        cp lv_micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8/partition_table/partition-table.bin ./artifacts/

    - name: Generate Tag
      id: tag
      run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ env.TAG_NAME }}
        title: "Release for version ${{ env.TAG_NAME }}"
        files: ./artifacts/*
