name: ESP32 Port

on:
  push:
    branches:
      - main  # Cambia esto según tu rama principal
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_idf44:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Clone lv_micropython repository
        run: git clone https://github.com/lvgl/lv_micropython.git

      - name: Initialize lv_bindings submodule
        run: cd lv_micropython && git submodule update --init --recursive lib/lv_bindings
        
      - name: Copy Board Configuration
        run: |
          cp -r ESP32_GENERIC_S3_N16R8 lv_micropython/ports/esp32/boards/
        
      - name: Install packages
        run: cd lv_micropython && source tools/ci.sh && ci_esp32_idf44_setup

      - name: Set Up ESP-IDF Environment
        run: |
          cd lv_micropython
          source tools/ci.sh
          source $IDF_PATH/export.sh
          echo "PATH=$PATH"  # Verifica que el PATH incluya el directorio de idf.py

      - name: Build for Custom Board
        run: |
          cd lv_micropython
          source tools/ci.sh
          make ${MAKEOPTS} -C ports/esp32 BOARD=ESP32_GENERIC_S3_N16R8
        
      #- name: Build
       # run: cd lv_micropython && source tools/ci.sh && ci_esp32_build

      - name: Mover binarios
        run: |
          mkdir -p ./artifacts
          cp micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8/micropython.bin ./artifacts/
          cp micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8/bootloader/bootloader.bin ./artifacts/
          cp micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8/partition_table/partition-table.bin ./artifacts/

      - name: Generate Tag
        id: tag
        run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
        
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ env.TAG_NAME }}  # Usa el nombre del tag generado
          title: "Release for version ${{ env.TAG_NAME }}"
          files: ./artifacts/*
